feat(*): Add npm as an alternative package manager and add playwright-init command (#15)
* feat(package manager): Add npm as alternative to yarn

* feat(*): Add playwright-init command

* fix(install): Fix playwright-install for npm

* test(*): Fix tests

* docs(README): Update readme

diff --git a/commands/playwright/playwright b/commands/playwright/playwright
--- a/commands/playwright/playwright
+++ b/commands/playwright/playwright
@@ -14,4 +14,12 @@ cd "${PLAYWRIGHT_TEST_DIR}" || exit 1
 export PLAYWRIGHT_BROWSERS_PATH=0
 PRE="sudo -u pwuser PLAYWRIGHT_BROWSERS_PATH=0 "
 
-$PRE yarn playwright "$@"
+if [ -f "package-lock.json" ]; then
+  $PRE npx playwright "$@"
+elif [ -f "yarn.lock" ]; then
+  $PRE yarn playwright "$@" 
+else
+  echo "ERROR: could not find lock file for a supported package manager (npm, yarn) in '${PLAYWRIGHT_TEST_DIR}'"
+  echo "Please run 'ddev playwright-install' or 'ddev playwright-init' to install playwright."
+  exit 1
+fi
